/**
 * Static mapping of variant column name -> group label.
 * Sourced from group_columns.xlsx.
 */
export const COLUMN_TO_GROUP = {
  "Chr": "Genomic Coordinates",
  "Start": "Genomic Coordinates",
  "End": "Genomic Coordinates",
  "Ref": "Genomic Coordinates",
  "Alt": "Genomic Coordinates",
  "Func.refGene": "Functional annotation",
  "Gene.refGene": "Functional annotation",
  "GeneDetail.refGene": "Functional annotation",
  "ExonicFunc.refGene": "Functional annotation",
  "AAChange.refGene": "Functional annotation",
  "SIFT_score": "Functional Impact",
  "SIFT_converted_rankscore": "Functional Impact",
  "SIFT_pred": "Functional Impact",
  "SIFT4G_score": "Functional Impact",
  "SIFT4G_converted_rankscore": "Functional Impact",
  "SIFT4G_pred": "Functional Impact",
  "Polyphen2_HDIV_score": "Functional Impact",
  "Polyphen2_HDIV_rankscore": "Functional Impact",
  "Polyphen2_HDIV_pred": "Functional Impact",
  "Polyphen2_HVAR_score": "Functional Impact",
  "Polyphen2_HVAR_rankscore": "Functional Impact",
  "Polyphen2_HVAR_pred": "Functional Impact",
  "LRT_score": "Functional Impact",
  "LRT_converted_rankscore": "Functional Impact",
  "LRT_pred": "Functional Impact",
  "LRT_Omega": "Functional Impact",
  "MutationTaster_score": "Functional Impact",
  "MutationTaster_converted_rankscore": "Functional Impact",
  "MutationTaster_pred": "Functional Impact",
  "MutationAssessor_score": "Functional Impact",
  "MutationAssessor_rankscore": "Functional Impact",
  "MutationAssessor_pred": "Functional Impact",
  "FATHMM_score": "Functional Impact",
  "FATHMM_converted_rankscore": "Functional Impact",
  "FATHMM_pred": "Functional Impact",
  "PROVEAN_score": "Functional Impact",
  "PROVEAN_converted_rankscore": "Functional Impact",
  "PROVEAN_pred": "Functional Impact",
  "VEST4_score": "Functional Impact",
  "VEST4_rankscore": "Functional Impact",
  "MetaSVM_score": "Functional Impact",
  "MetaSVM_rankscore": "Functional Impact",
  "MetaSVM_pred": "Functional Impact",
  "MetaLR_score": "Functional Impact",
  "MetaLR_rankscore": "Functional Impact",
  "MetaLR_pred": "Functional Impact",
  "Reliability_index": "Functional Impact",
  "MetaRNN_score": "Functional Impact",
  "MetaRNN_rankscore": "Functional Impact",
  "MetaRNN_pred": "Functional Impact",
  "M-CAP_score": "Functional Impact",
  "M-CAP_rankscore": "Functional Impact",
  "M-CAP_pred": "Functional Impact",
  "REVEL_score": "Functional Impact",
  "REVEL_rankscore": "Functional Impact",
  "MutPred_score": "Functional Impact",
  "MutPred_rankscore": "Functional Impact",
  "MVP_score": "Functional Impact",
  "MVP_rankscore": "Functional Impact",
  "gMVP_score": "Functional Impact",
  "gMVP_rankscore": "Functional Impact",
  "MPC_score": "Functional Impact",
  "MPC_rankscore": "Functional Impact",
  "PrimateAI_score": "Functional Impact",
  "PrimateAI_rankscore": "Functional Impact",
  "PrimateAI_pred": "Functional Impact",
  "DEOGEN2_score": "Functional Impact",
  "DEOGEN2_rankscore": "Functional Impact",
  "DEOGEN2_pred": "Functional Impact",
  "BayesDel_addAF_score": "Functional Impact",
  "BayesDel_addAF_rankscore": "Functional Impact",
  "BayesDel_addAF_pred": "Functional Impact",
  "BayesDel_noAF_score": "Functional Impact",
  "BayesDel_noAF_rankscore": "Functional Impact",
  "BayesDel_noAF_pred": "Functional Impact",
  "ClinPred_score": "Functional Impact",
  "ClinPred_rankscore": "Functional Impact",
  "ClinPred_pred": "Functional Impact",
  "LIST-S2_score": "Functional Impact",
  "LIST-S2_rankscore": "Functional Impact",
  "LIST-S2_pred": "Functional Impact",
  "VARITY_R_score": "Functional Impact",
  "VARITY_R_rankscore": "Functional Impact",
  "VARITY_ER_score": "Functional Impact",
  "VARITY_ER_rankscore": "Functional Impact",
  "VARITY_R_LOO_score": "Functional Impact",
  "VARITY_R_LOO_rankscore": "Functional Impact",
  "VARITY_ER_LOO_score": "Functional Impact",
  "VARITY_ER_LOO_rankscore": "Functional Impact",
  "ESM1b_score": "Functional Impact",
  "ESM1b_rankscore": "Functional Impact",
  "ESM1b_pred": "Functional Impact",
  "EVE_score": "Functional Impact",
  "EVE_rankscore": "Functional Impact",
  "AlphaMissense_score": "Functional Impact",
  "AlphaMissense_rankscore": "Functional Impact",
  "AlphaMissense_pred": "Functional Impact",
  "Aloft_pred": "Functional Impact",
  "Aloft_Confidence": "Functional Impact",
  "CADD_raw": "Functional Impact",
  "CADD_raw_rankscore": "Functional Impact",
  "CADD_phred": "Functional Impact",
  "DANN_score": "Functional Impact",
  "DANN_rankscore": "Functional Impact",
  "fathmm-MKL_coding_score": "Functional Impact",
  "fathmm-MKL_coding_rankscore": "Functional Impact",
  "fathmm-MKL_coding_pred": "Functional Impact",
  "fathmm-MKL_coding_group": "Functional Impact",
  "fathmm-XF_coding_score": "Functional Impact",
  "fathmm-XF_coding_rankscore": "Functional Impact",
  "fathmm-XF_coding_pred": "Functional Impact",
  "Eigen-raw_coding": "Functional Impact",
  "Eigen-raw_coding_rankscore": "Functional Impact",
  "Eigen-phred_coding": "Functional Impact",
  "Eigen-PC-raw_coding": "Functional Impact",
  "Eigen-PC-raw_coding_rankscore": "Functional Impact",
  "Eigen-PC-phred_coding": "Functional Impact",
  "GenoCanyon_score": "Functional Impact",
  "GenoCanyon_rankscore": "Functional Impact",
  "integrated_fitCons_score": "Functional Impact",
  "integrated_fitCons_rankscore": "Functional Impact",
  "integrated_confidence_value": "Functional Impact",
  "GM12878_fitCons_score": "Functional Impact",
  "GM12878_fitCons_rankscore": "Functional Impact",
  "GM12878_confidence_value": "Functional Impact",
  "H1-hESC_fitCons_score": "Functional Impact",
  "H1-hESC_fitCons_rankscore": "Functional Impact",
  "H1-hESC_confidence_value": "Functional Impact",
  "HUVEC_fitCons_score": "Functional Impact",
  "HUVEC_fitCons_rankscore": "Functional Impact",
  "HUVEC_confidence_value": "Functional Impact",
  "LINSIGHT": "Functional Impact",
  "LINSIGHT_rankscore": "Functional Impact",
  "GERP++_NR": "Conservation Score",
  "GERP++_RS": "Conservation Score",
  "GERP++_RS_rankscore": "Conservation Score",
  "phyloP100way_vertebrate": "Conservation Score",
  "phyloP100way_vertebrate_rankscore": "Conservation Score",
  "phyloP470way_mammalian": "Conservation Score",
  "phyloP470way_mammalian_rankscore": "Conservation Score",
  "phyloP17way_primate": "Conservation Score",
  "phyloP17way_primate_rankscore": "Conservation Score",
  "phastCons100way_vertebrate": "Conservation Score",
  "phastCons100way_vertebrate_rankscore": "Conservation Score",
  "phastCons470way_mammalian": "Conservation Score",
  "phastCons470way_mammalian_rankscore": "Conservation Score",
  "phastCons17way_primate": "Conservation Score",
  "phastCons17way_primate_rankscore": "Conservation Score",
  "SiPhy_29way_pi": "Conservation Score",
  "SiPhy_29way_logOdds": "Conservation Score",
  "SiPhy_29way_logOdds_rankscore": "Conservation Score",
  "bStatistic": "Conservation Score",
  "bStatistic_converted_rankscore": "Conservation Score",
  "Interpro_domain": "Protein Domain",
  "GTEx_V8_eQTL_gene": "nan",
  "GTEx_V8_eQTL_tissue": "nan",
  "GTEx_V8_sQTL_gene": "nan",
  "GTEx_V8_sQTL_tissue": "nan",
  "eQTLGen_snp_id": "nan",
  "gnomad41_genome_AF": "Population Frequency",
  "gnomad41_genome_AF_raw": "Population Frequency",
  "gnomad41_genome_AF_XX": "Population Frequency",
  "gnomad41_genome_AF_XY": "Population Frequency",
  "gnomad41_genome_AF_grpmax": "Population Frequency",
  "gnomad41_genome_faf95": "Population Frequency",
  "gnomad41_genome_faf99": "Population Frequency",
  "gnomad41_genome_fafmax_faf95_max": "Population Frequency",
  "gnomad41_genome_fafmax_faf99_max": "Population Frequency",
  "gnomad41_genome_AF_afr": "Population Frequency",
  "gnomad41_genome_AF_ami": "Population Frequency",
  "gnomad41_genome_AF_amr": "Population Frequency",
  "gnomad41_genome_AF_asj": "Population Frequency",
  "gnomad41_genome_AF_eas": "Population Frequency",
  "gnomad41_genome_AF_fin": "Population Frequency",
  "gnomad41_genome_AF_mid": "Population Frequency",
  "gnomad41_genome_AF_nfe": "Population Frequency",
  "gnomad41_genome_AF_remaining": "Population Frequency",
  "gnomad41_genome_AF_sas": "Population Frequency",
  "avsnp150": "Genomic Coordinates",
  "InterVar_automated": "Clinical Annotation",
  "PVS1": "Clinical Annotation",
  "PS1": "Clinical Annotation",
  "PS2": "Clinical Annotation",
  "PS3": "Clinical Annotation",
  "PS4": "Clinical Annotation",
  "PM1": "Clinical Annotation",
  "PM2": "Clinical Annotation",
  "PM3": "Clinical Annotation",
  "PM4": "Clinical Annotation",
  "PM5": "Clinical Annotation",
  "PM6": "Clinical Annotation",
  "PP1": "Clinical Annotation",
  "PP2": "Clinical Annotation",
  "PP3": "Clinical Annotation",
  "PP4": "Clinical Annotation",
  "PP5": "Clinical Annotation",
  "BA1": "Clinical Annotation",
  "BS1": "Clinical Annotation",
  "BS2": "Clinical Annotation",
  "BS3": "Clinical Annotation",
  "BS4": "Clinical Annotation",
  "BP1": "Clinical Annotation",
  "BP2": "Clinical Annotation",
  "BP3": "Clinical Annotation",
  "BP4": "Clinical Annotation",
  "BP5": "Clinical Annotation",
  "BP6": "Clinical Annotation",
  "BP7": "Clinical Annotation",
  "CLNALLELEID": "Clinical Annotation",
  "CLNDN": "Clinical Annotation",
  "CLNDISDB": "Clinical Annotation",
  "CLNREVSTAT": "Clinical Annotation",
  "CLNSIG": "Clinical Annotation",
  "ONCDN": "Cancer Annotation",
  "ONCDISDB": "Cancer Annotation",
  "ONCREVSTAT": "Cancer Annotation",
  "ONC": "Cancer Annotation",
  "SCIDN": "Cancer Annotation",
  "SCIDISDB": "Cancer Annotation",
  "SCIREVSTAT": "Cancer Annotation",
  "SCI": "Cancer Annotation",
  "ID": "Genomic Coordinates",
  "Consequence": "Functional annotation",
  "SYMBOL": "Functional annotation",
  "Gene": "Functional annotation",
  "Feature": "Functional annotation",
  "HGVSp": "Functional annotation",
  "AA_pos": "Functional annotation",
  "Ref_aa": "Functional annotation",
  "Alt_aa": "Functional annotation",
  "prediction": "Functional Impact",
  "LoGoFunc_neutral": "Functional Impact",
  "LoGoFunc_GOF": "Functional Impact",
  "LoGoFunc_LOF": "Functional Impact",
  "regsnp_fpr": "Functional Impact",
  "regsnp_disease": "Functional Impact",
  "regsnp_splicing_site": "Functional Impact",
  "dbscSNV_ADA_SCORE": "Functional Impact",
  "dbscSNV_RF_SCORE": "Functional Impact",
  "omim_id": "OMIM Annotation",
  "GT": "Sample Information",
  "AD": "Sample Information",
  "DP": "Sample Information",
  "AF": "Sample Information",
  "Zygosity": "Sample Information",
};

/** Fallback bucket for columns not in COLUMN_TO_GROUP. */
export const OTHER_GROUP = "Other";

/**
 * Display order for groups — most clinically relevant first.
 * "Other" always sits last (appended dynamically if any unknown columns exist).
 */
export const GROUP_ORDER = [
  "Clinical Annotation",
  "Population Frequency",
  "Functional annotation",
  "Functional Impact",
  "Conservation Score",
  "Cancer Annotation",
  "Sample Information",
  "Genomic Coordinates",
  "OMIM Annotation",
  "Protein Domain",
];

/** Group a flat list of column names into { groupName: string[] } in display order. */
export function groupColumns(columns) {
  const buckets = {};
  for (const col of columns) {
    const group = COLUMN_TO_GROUP[col] || OTHER_GROUP;
    if (!buckets[group]) buckets[group] = [];
    buckets[group].push(col);
  }
  const ordered = [];
  for (const g of GROUP_ORDER) {
    if (buckets[g]) ordered.push([g, buckets[g]]);
  }
  if (buckets[OTHER_GROUP]) ordered.push([OTHER_GROUP, buckets[OTHER_GROUP]]);
  return ordered;
}

